### ISSUE TITLE
Error: invalid element type

### ISSUE THREAD

**Issue by niccolomineo** [Le0Developer/react-turnstile#11]
Hi there, I am getting the following error:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object
```

I did import the component the way it is mentioned in the README: 🤔

```
import Turnstile from "react-turnstile";
```

What could be the culprit?

**Comment by Yaroslavpnts** [comment]
Why this issue was closed?
I have the same error, how to fix it?
