### ISSUE TITLE
Component not displayed on initial render

### ISSUE THREAD

**Issue by Maxou44** [Le0Developer/react-turnstile#4]
Hello,

When I force-refresh my app, the script is loaded (I can see it in the network tab) but the component will never be display, I just have empty ```<div>``` element. If I navigate in my app and go back to the page, the component will properly appears. It looks like the script setup don't correctly trigger a rerender.

It's possible to work around the problem by adding the script in the HTML:
```html
<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>
```

**Comment by Le0Developer** [comment]
The issue seems to be related to `ref.current` being null when the turnstile js is loaded.
Took me around half an hour to reproduce.

Potential fix is adding `ref` as prop, but I will have to test for another half an hour to see if that really fixes it.

**Comment by Le0Developer** [comment]
Narrowed it down to `createRef` and using `useRef` fixed it.
Will release fix soon.

**Comment by Le0Developer** [comment]
v1.0.3 has been released on NPM.

**Comment by Maxou44** [comment]
Awesome ! Thanks a lot ❤️
