### ISSUE TITLE
Reset component by using ref.current.reset()

### ISSUE THREAD

**Issue by exdeusdev** [Le0Developer/react-turnstile#7]
Hi, how i can pas ref into Turnstile component ?
For an example:
```JS
import { useRef } from "react";
import Turnstile from "react-turnstile";

const TurnstileWidget() {
  const ref = useRef(null)
  return (
    <Turnstile
      ref={ref}
      sitekey="1x00000000000000000000AA"
      onVerify={(token) => alert(token)}
    />
  );
}
```
So i can call reset function with `ref.current.reset()`

Already following this guide [How to get widget id?](https://github.com/Le0Developer/react-turnstile/issues/5), but i want more clean code to handle the component. I think it would be great and can support `remove`, `getResponse`.
Thankyou 👍

**Comment by Le0Developer** [comment]
Published in v1.0.6 just now.

Note that the correct call to reset turnstile is `turnstile.reset(ref.current);`, not `ref.current.reset();`.
